name: 'Anansi Github Action'
description: 'Action for crawling and indexing a website using Anansi'
author: 'anansi.js'
inputs:
  configPath:
    required: true
    description: 'path to the crawler config file'
runs:
  using: "composite"
  steps:
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version
    - name: Check out git repository
      uses: actions/checkout@v3

    - name: Now calling the node action in directory ./actions/node-action
      uses: anansi-js/anansi-github-action/actions/node-action@main
      with:
        configPath: ${{ inputs.configPath }}
